### ISSUE TITLE
Question: why does `Janode setup error` force the websocket connection to be closed?

### ISSUE THREAD

**Issue by alvitoraidhy** [meetecho/janode#4]
Hi. I was developing an app with Janode and by mistake I tried to connect to a nonexistent room. However I didn't expect the error to make the websocket close itself without reconnecting. I'm using this connection for all of my sessions and this just closes them all basically. May I know the reason for that and how can I stop it to close?

```
[36mbackend_1   |[0m 2022-03-07T13:03:19.911Z - INFO : [transport-ws.js] [8999818924408386] closing websocket
[36mbackend_1   |[0m error while joining a tour:  Error: 426 No such room (5332351842943423)
[36mbackend_1   |[0m     at VideoRoomHandle.handleMessage (file:///usr/src/server/node_modules/janode/src/plugins/videoroom-plugin.js:304:33)
[36mbackend_1   |[0m     at VideoRoomHandle._handleMessage (file:///usr/src/server/node_modules/janode/src/handle.js:246:19)
[36mbackend_1   |[0m     at Session._handleMessage (file:///usr/src/server/node_modules/janode/src/session.js:264:14)
[36mbackend_1   |[0m     at Connection._handleMessage (file:///usr/src/server/node_modules/janode/src/connection.js:200:17)
[36mbackend_1   |[0m     at WebSocket.<anonymous> (file:///usr/src/server/node_modules/janode/src/transport-ws.js:166:26)
[36mbackend_1   |[0m     at WebSocket.onMessage (/usr/src/server/node_modules/ws/lib/event-target.js:199:18)
[36mbackend_1   |[0m     at WebSocket.emit (node:events:520:28)
[36mbackend_1   |[0m     at Receiver.receiverOnMessage (/usr/src/server/node_modules/ws/lib/websocket.js:1137:20)
[36mbackend_1   |[0m     at Receiver.emit (node:events:520:28)
[36mbackend_1   |[0m     at Receiver.dataMessage (/usr/src/server/node_modules/ws/lib/receiver.js:528:14) {
[36mbackend_1   |[0m   _code: 426
[36mbackend_1   |[0m }
[36mbackend_1   |[0m 2022-03-07T13:03:19.931Z - INFO : [janus.js] [172.20.0.8:58336] disconnected socket
[36mbackend_1   |[0m 2022-03-07T13:03:19.933Z - ERROR: [transport-ws.js] [8999818924408386] websocket send error (WebSocket is not open: readyState 2 (CLOSING))
[36mbackend_1   |[0m 2022-03-07T13:03:19.940Z - INFO : [transport-ws.js] [8999818924408386] websocket closed code=1005 reason= clean=true
[36mbackend_1   |[0m 2022-03-07T13:03:19.940Z - INFO : [transport-ws.js] [8999818924408386] websocket ping task disabled
[36mbackend_1   |[0m 2022-03-07T13:03:19.941Z - INFO : [tmanager.js] [8999818924408385] clearing transaction manager
[36mbackend_1   |[0m 2022-03-07T13:03:19.941Z - INFO : Connection with Janus closed
```

**Comment by atoppi** [comment]
The videoroom plugin does not close the transport connection in case of errors.
The `connection.close()` is probably coming from the application code.

For example in the videoroom example there is `connection.close` call in the catch block of the initialization.
https://github.com/meetecho/janode/blob/master/examples/videoroom/src/index.js#L95-L97

**Comment by alvitoraidhy** [comment]
> The videoroom plugin does not close the transport connection in case of errors. The `connection.close()` is probably coming from the application code.
> 
> For example in the videoroom example there is `connection.close` call in the catch block of the initialization. https://github.com/meetecho/janode/blob/master/examples/videoroom/src/index.js#L95-L97

Oh right thanks. I did use the example as the base, I should've looked at the code more thoroughly. I'll close this now
